### ISSUE TITLE
KSU v1.0啦。

### ISSUE THREAD

**Issue by itachiccc** [fei-ke/android_kernel_samsung_sm8550#3]
大佬，KSU v1.0了。期待你的更新哈哈哈
----
自己编译了一下KSU_v1.0.1，内核版本号后缀多了个dirty要怎么解决啊。

**Comment by mio-19** [comment]
samsung firmware也更新了
CXE3

**Comment by xiatianx** [comment]
别急伙计们 三星源码库刚更新到S9180ZCU2CXCF

**Comment by mio-19** [comment]
源码库这个月也不更新内核😿

**Comment by mio-19** [comment]
低版本内核能配高版本firmware嘛

**Comment by itachiccc** [comment]
> 低版本内核能配高版本firmware嘛

这老哥的也不错，但是没开源不能自己折腾了。
https://github.com/qlenlen/android_kernel_samsung_sm8550/releases

**Comment by itachiccc** [comment]
> 源码库这个月也不更新内核😿

那个老哥好像还在作妖。死活不放源码出来= ，=
https://github.com/qlenlen/android_kernel_samsung_sm8550?tab=readme-ov-file#-kernel-source-guideline

**Comment by fei-ke** [comment]
dirty 是表示 git 工作空间有未提交的变更

**Comment by mio-19** [comment]
Why was this issue closed

**Comment by fei-ke** [comment]
> Why was this issue closed

Since KernelSU supports LKM, Using the LKM version with Kernel is recommended: [gki_kernel_5.15.123-android13-8](https://github.com/fei-ke/android_kernel_samsung_sm8550/releases/tag/gki_kernel_5.15.123-android13-8)

Anyway, I will upload a version with KernelSU latest stable version, in case someone needs it.
